#!/bin/bash
# /etc/init.d/hx711

### BEGIN INIT INFO
# sudo chmod +x /etc/init.d/hx711
# sudo service hx711 start_hx711
# sudo service hx711 stop
# 设置开机启动
# sudo update-rc.d hx711 defaults
### END INIT INFO

case "$1" in
start_hx711)
  echo "Starting HX711"
  /home/pi/hx711/main.py &
  ;;
stop)
  echo "Stopping hx711"
  kill $(ps aux | grep -m 1 'python /home/pi/hx711/main.py' | awk '{ print $2 }')
  ;;
*)
  echo "Usage: service hx711 start|stop"
  exit 1
  ;;
esac
exit 0
